version: "3.6"
services:
  nats_streaming:
    image: nats-streaming:latest
    ports:
      - '127.0.0.1:4223:4222'
      - '127.0.0.1:8223:8222'
    networks:
      - my_network

  db:
   build: "postgresql"
   restart: always
   environment:
        POSTGRES_DB: "test_db"
        POSTGRES_USER: "testUser"
        POSTGRES_PASSWORD: "password"
   ports:
     - '127.0.0.1:5432:5432'
   networks:
    - my_network

  service:
    restart: always
    build: './service/'
    environment:
      db: "test_db"
      password: "password"
      user: "testUser"
    command: ["./wait-for-postgres.sh", "db", "./build/service"]
    ports:
      - '127.0.0.1:8080:8080'
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

